### ISSUE TITLE
Error at delete Attribute

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_translatedurl#14]
Error at delete Attribute

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message ID missing or given object not of type 'ModelInterface'. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/DefaultDataProvider.php on line 272

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/DeleteHandler.php(270): ContaoCommunityAlliance\DcGeneral\Data\DefaultDataProvider->delete(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/DeleteHandler.php(75): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler->deepDelete(Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId))
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(55): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler->process()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractEnvironmentAwareHandler.php(72): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(153): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(75): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
```

**Comment by discordier** [comment]
Not a bug in MM or this attribute but a bug in dcg delete handling
